spring:
  application:
    name: gateway-service
  cloud:
    config:
      discovery:
        serviceId: config-server
        enabled: true
    gateway:
      routes:
        - id: users-service
          uri: lb://users-service
          predicates:
            - Path=/users
  config:
   import: "optional:configserver:"


server:
  port: 8084
