spring:
  application:
    name: gateway-service
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server
    gateway:
      routes:
        - id: users-service
          uri: lb://users-service
          predicates:
            - Path=/users

  config:
    import: "optional:configserver:"

server:
  port: 8084

